kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  brokers: ${kafka.bootstrap-servers}
  group.id: test
  auto.offset.reset: earliest
  fastLane:
    topic: fast-lane-topic
    pollTimeout: 1000
  slowLane:
    topic: slow-lane-topic
    pollTimeout: 1000
