kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  groupId: "tmp"
  fastLane:
    topic: tmp-fastLane
    poll:
      timeout.ms: 10000
      interval.ms: 1000
      pool.size: 5
  slowLane:
    topic: tmp-slowLane
    poll:
      timeout.ms: 10000
      interval.ms: 2000
      pool.size: 1
