kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  groupId: "tmp"
  fastLane:
    topic: tmp-fastLane
  slowLane:
    topic: tmp-slowLane
    backOffPeriod: 2000
    retryMaxAttempts: 3
    triggerTime.ms: 5000
#  bootstrap-servers: localhost:9092
#  topic:
#    helloworld: helloworld.t
