kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  brokers: ${kafka.bootstrap-servers}
  group.id: test
  auto.offset.reset: earliest
  fastLane:
    topic: fast-lane-topic
    poll:
      interval.ms: 1500
      initialDelay.ms: 3000
      timeout.ms: 3000
      pool.size: 6
      max.records: 1
  slowLane:
    topic: slow-lane-topic
    poll:
      interval.ms: 3000
      initialDelay.ms: 3000
      timeout.ms: 6000
      pool.size: 1
      max.records: 1
