kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  groupId: "tmp"
  retry:
    initial.retention.seconds: 5
    retention.max.seconds: 30
  fastLane:
    topic: tmp-fastLane
    poll:
      timeout.ms: 5000
      interval.ms: 1000
      initialDelay.ms: 0
      pool.size: 5
      max.records: 3
  slowLane:
    topic: tmp-slowLane
    poll:
      timeout.ms: 10000
      interval.ms: 2000
      initialDelay.ms: 0
      pool.size: 2
      max.records: 2
